steps:  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build docker package'
    args: [
      'build',
      '-t',
      '${_ARTIFACT_REGISTRY_URL}/api:${COMMIT_SHA}',
      './api'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker push'
    args: ['push', '-a', '${_ARTIFACT_REGISTRY_URL}/api']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy to cloud run'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'api',
        '--image',
        '${_ARTIFACT_REGISTRY_URL}/api:${COMMIT_SHA}',
        '--region',
        'europe-west3',
        '--platform',
        'managed',
        '--set-env-vars',
        'PROJECT_NUMBER=${PROJECT_NUMBER},PROJECT_ID=${_PROJECT_ID}',        
        '--allow-unauthenticated'
      ]

images:
  - '${_ARTIFACT_REGISTRY_URL}/api:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
