steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'set .env file'
    entrypoint: bash
    args:
      - -c
      - |
        touch ./frontend/.env
        echo "PROJECT_NUMBER=${_PROJECT_NUMBER}" > ./frontend/.env
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build docker package'
    args: [
        'build',
        '-t',
        '${_ARTIFACT_REGISTRY_URL}/frontend:${COMMIT_SHA}',
        './frontend'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker push'
    args: ['push', '-a', '${_ARTIFACT_REGISTRY_URL}/frontend']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy to cloud run'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'frontend',
        '--image',
        '${_ARTIFACT_REGISTRY_URL}/frontend:${COMMIT_SHA}',
        '--region',
        'europe-west3',
        '--platform',
        'managed',
      ]

images:
  - '${_ARTIFACT_REGISTRY_URL}/frontend:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
