steps:  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build docker package'
    args: [
      'build',
      '-t',
      '${_ARTIFACT_REGISTRY_URL}:${COMMIT_SHA}',
      './api'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker push'
    args: ['push', '-a', '${_ARTIFACT_REGISTRY_URL}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy to cloud run'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'api',
        '--image',
        '${_ARTIFACT_REGISTRY_URL}:${COMMIT_SHA}',
        '--region',
        'europe-west3',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - '${_ARTIFACT_REGISTRY_URL}:${COMMIT_SHA}'

substitutions:
  _ARTIFACT_REGISTRY_URL: europe-west3-docker.pkg.dev/me-test-project-489908/api/build

options:
  logging: CLOUD_LOGGING_ONLY